//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.1.
// PicoPico_res.rc

#define IDD_MAIN                            100

#define IDI_MAIN                            1

#define IDR_MAINMENU                        100

#define IDS_TITLE                           100
#define IDS_NONE                            101
#define IDS_TIP                             102

#define ID_EXIT                             100
#define ID_CONFIG                           101
#define ID_ENABLE                           102
#define ID_DISABLE                          103
#define ID_HIDE                             104

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     105
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
